esphome:
  # name: "${name}"
  # friendly_name: "${friendly_name}"
  # comment: "${device_description} by Lewa-Reka & HarveyDent https://github.com/HarveyDent1/esphome-deye-inverter"
  # project:
  #   name: "lewa-reka-hervey-dent.esphome-pv-inverter"
  #   version: "0.3.0"

logger:
  level: WARN

api:
  encryption:
    key: ${api_key}
  on_client_disconnected:
    - delay: ${safe_mode_delay}
    - if:
        condition:
          not: api.connected
        then:
          - logger.log: "Lost connection to HomeAssistant API - Activating safe mode"
          - script.execute: set_safe_modbus_registers

  on_client_connected:
    - logger.log: "Connection to HomeAssistant API restored"

ota:
  - platform: esphome
    password: ${ota_password}

# wifi:
#   ssid: ${wifi_ssid}
#   password: ${wifi_password}
#   manual_ip: ## Set if you need static IP. Microtic routers needs it
#     static_ip: 172.16.20.30
#     gateway: 172.16.20.1
#     subnet: 255.255.255.0
#     dns1: 172.16.1.2
#     dns2: 172.16.1.1
#   ap:
#     ssid: "${friendly_name} Fallback Hotspot"
#     password: ${fallback_password}}

captive_portal:

uart:
  id: modbus_uart 
  baud_rate: 9600 #for Deye 1P
  # baud_rate: 19200 #for Deye 3P
  stop_bits: 1

modbus:
  id: modbus_1
  uart_id: modbus_uart

modbus_controller:
  - id: ${modbus_controller_id} 
    address: ${modbus_inverter_address}
    modbus_id: modbus_1 
    setup_priority: -10 
    update_interval: 5s 
    command_throttle: 60ms
    offline_skip_updates: 3
